version: "3.7"  # optional since v1.27.0
services:
  web:
    container_name: django_aplication

    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"